### ISSUE TITLE
Aurora Todo List

### ISSUE THREAD

**Issue by chrismcdermut** [chrismcdermut/Ninjascripts#6]
Parameters for Chris to Adjust:

**Days to lookback:**
-On calendar days: 7,14,21 (all at once)
-On calendar days: 7  
-On trading days: 1,2,3,4,5  (all at once)
-On trading days: 1  
**Swing strength:**
-5
-3
-10
-25
-Whatever is the equivalent to 5 x 3 minute bars, but for different bar time periods (e.g. for 1 minute x 15 swing strength = 3minute x 5 swing strength)
**Bar time periods:**
-1
-3
-5
-15
-1 hour

**Iterations:**
- [ ] 15BP 7,14,21CD 3SS
- [ ] 1BP 7,14,21CD 3SS
- [ ] 3BP 7,14,21CD 3SS
- [ ] 5BP 7,14,21CD 3SS
- [ ] 1BP 7CD 3SS
- [ ] 3BP 7CD 3SS
- [ ] 5BP 7CD 3SS
- [ ] 15BP 7CD 3SS
- [ ] 1BP 12345TD 3SS
- [ ] 3BP 12345TD 3SS
- [ ] 5BP 12345TD 3SS
- [ ] 15BP 12345TD 3SS
- [ ] 1BP 1TD 3SS
- [ ] 3BP 1TD 3SS
- [ ] 5BP 1TD 3SS
- [ ] 15BP 1TD 3SS
- [ ] 1BP 7,14,21CD 5SS
- [ ] 3BP 7,14,21CD 5SS
- [ ] 5BP 7,14,21CD 5SS
- [ ] 15BP 7,14,21CD 5SS
- [ ] 1BP 7CD 5SS
- [ ] 3BP 7CD 5SS
- [ ] 5BP 7CD 5SS
- [ ] 15BP 7CD 5SS
- [ ] 1BP 12345TD 5SS
- [ ] 3BP 12345TD 5SS
- [ ] 5BP 12345TD 5SS
- [ ] 15BP 12345TD 5SS
- [ ] 1BP 1TD 5SS
- [ ] 3BP 1TD 5SS
- [ ] 5BP 1TD 5SS
- [ ] 15BP 1TD 5SS
- [ ] 1BP 7,14,21CD 10SS
- [ ] 3BP 7,14,21CD 10SS
- [ ] 5BP 7,14,21CD 10SS
- [ ] 15BP 7,14,21CD 10SS
- [ ] 1BP 7CD 10SS
- [ ] 3BP 7CD 10SS
- [ ] 5BP 7CD 10SS
- [ ] 15BP 7CD 10SS
- [ ] 1BP 12345TD 10SS
- [ ] 3BP 12345TD 10SS
- [ ] 5BP 12345TD 10SS
- [ ] 15BP 12345TD 10SS
- [ ] 1BP 1TD 10SS
- [ ] 3BP 1TD 10SS
- [ ] 5BP 1TD 10SS
- [ ] 15BP 1TD 10SS
- [ ] 1BP 7,14,21CD 25SS
- [ ] 3BP 7,14,21CD 25SS
- [ ] 5BP 7,14,21CD 25SS
- [ ] 15BP 7,14,21CD 25SS
- [ ] 1BP 7CD 25SS
- [ ] 3BP 7CD 25SS
- [ ] 5BP 7CD 25SS
- [ ] 15BP 7CD 25SS
- [ ] 1BP 12345TD 25SS
- [ ] 3BP 12345TD 25SS
- [ ] 5BP 12345TD 25SS
- [ ] 15BP 12345TD 25SS
- [ ] 1BP 1TD 25SS
- [ ] 3BP 1TD 25SS
- [ ] 5BP 1TD 25SS
- [ ] 15BP 1TD 25SS
- [ ] 60BP 7CD 3SS
- [ ] 60BP 1TD 3SS
- [ ] 60BP 12345TD 3SS
- [ ] 60BP 1TD 5SS
- [ ] 60BP 7,14,21CD 5SS
- [ ] 60BP 12345TD 5SS
- [ ] 60BP 7,14,21CD 10SS
- [ ] 60BP 7,14,21CD 3SS
- [ ] 60BP 7CD 5SS
- [ ] 60BP 7CD 10SS
- [ ] 60BP 12345TD 10SS
- [ ] 60BP 1TD 10SS
- [ ] 60BP 7,14,21CD 25SS
- [ ] 60BP 7CD 25SS
- [ ] 60BP 12345TD 25SS
- [ ] 60BP 1TD 25SS
