### ISSUE TITLE
Aurora Todo

### ISSUE THREAD

**Issue by chrismcdermut** [chrismcdermut/Ninjascripts#7]
**Misc:**
- [x] Change to one bar back
- [x] make directory automatic
- [x] make Bar period automatic
